Agency/Controllers/EmploymentTypeController.cs
using CRM.ViewModel;
using CRM.Auth;
using CRM.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CRM.Helpers;

namespace CRM.Controllers
{
    [CustomAuthenticationFilter]
    public class EmploymentTypeController : Controller
    {
        CRMDbContext db = new CRMDbContext();

        // GET: EmploymentType
        public ActionResult Index()
        {
            int companyId = Session["companyID"].ToString().ToInt();
            if (Request.IsAjaxRequest())
            {
                var draw = Request.Form.GetValues("draw").FirstOrDefault();
                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();
                //var from_date = Request.Form.GetValues("columns[0][search][value]")[0];
                //var to_date = Request.Form.GetValues("columns[1][search][value]")[0];
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;

                // Getting all data    
                var EmploymentTypeData = (from EmploymentType in db.EmploymentTypes
                                          join user in db.Users on EmploymentType.created_by equals user.id
                                          select new EmploymentTypeViewModel
                                          {
                                              id = EmploymentType.id,
                                              name = EmploymentType.name,
                                              description = EmploymentType.description,
                                              active = EmploymentType.active,
                                              created_at_string = EmploymentType.created_at.ToString(),
                                              company_id = user.company_id

                                          }).Where(et=>et.company_id == companyId);

                //Search    
                if (!string.IsNullOrEmpty(searchValue))
                {
                    EmploymentTypeData = EmploymentTypeData.Where(m => m.name.ToLower().Contains(searchValue.ToLower()) || m.id.ToString().ToLower().Contains(searchValue.ToLower()) ||
                     m.description.ToLower().Contains(searchValue.ToLower()));
                }

                //total number of rows count     
                var displayResult = EmploymentTypeData.OrderByDescending(u => u.id).Skip(skip)
                     .Take(pageSize).ToList();
                var totalRecords = EmploymentTypeData.Count();

                return Json(new
                {
                    draw = draw,
                    recordsTotal = totalRecords,
                    recordsFiltered = totalRecords,
                    data = displayResult

                }, JsonRequestBehavior.AllowGet);

            }

            return View();
        }

        [HttpPost]
        public JsonResult saveEmploymentType(EmploymentTypeViewModel EmploymentTypeVM)
        {

            if (EmploymentTypeVM.id == 0)
            {
                EmploymentType EmploymentType = AutoMapper.Mapper.Map<EmploymentTypeViewModel, EmploymentType>(EmploymentTypeVM);

                EmploymentType.created_at = DateTime.Now;
                EmploymentType.created_by = Session["id"].ToString().ToInt();

                db.EmploymentTypes.Add(EmploymentType);
                db.SaveChanges();
            }
            else
            {

                EmploymentType oldEmploymentType = db.EmploymentTypes.Find(EmploymentTypeVM.id);

                oldEmploymentType.name = EmploymentTypeVM.name;
                oldEmploymentType.updated_by = Session["id"].ToString().ToInt();
                oldEmploymentType.updated_at = DateTime.Now;

                db.Entry(oldEmploymentType).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }

            return Json(new { message = "done" }, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        public JsonResult deleteEmploymentType(int id)
        {
            EmploymentType EmploymentType = db.EmploymentTypes.Find(id);
            db.EmploymentTypes.Remove(EmploymentType);
            db.SaveChanges();

            return Json(new { message = "done" }, JsonRequestBehavior.AllowGet);
        }

    }
}

Agency/Views/EmploymentType/Index.cshtml
@using CRM.Enums;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="modal fade" id="manage_EmploymentType_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <form action="" method="post" enctype='multipart/form-data'>
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modal_title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-body">
                        <div class="form-row">
                            <input type="hidden" name="id" id="id" value="0" />

                            <div class="form-group col-md-12">
                                <label>name</label>
                                <input required name="name" id="name" type="text" class="form-control radius-30" />
                            </div>

                        </div>

                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </form>
</div>

<div class="page-header">
    <nav class="breadcrumb-one" aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0);">EmploymentType</a></li>
        </ol>
    </nav> <!-- we commented old button and add new button with the id of add resrvation in old dropdown menu-->
    <button class="special-btn" id="add_EmploymentType"><a href="javascript:void(0);">Add EmploymentType</a></button>
    <!--
        <div class="dropdown filter custom-dropdown-icon">
        <a class="dropdown-toggle btn" href="#" role="button" id="filterDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="text">More</span> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-down"><polyline points="6 9 12 15 18 9"></polyline></svg></a>

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="filterDropdown">
            <a class="dropdown-item" id="add_user" data-value="<span>Show</span> : Add User" href="javascript:void(0);">Add User</a>
        </div>
    </div>
    -->

</div>


<div class="row">
    <div class="form-group col-4">
        <input class="form-control" type="text" id="text_search" name="text_search" placeholder="Search">
    </div>
    <div class="form-group col-2">
        <button id="search" class="btn btn-primary px-3 radius-30">Search</button>
    </div>
    <div class="form-group col-2">
        <button id="reset" class="btn btn-danger px-3 radius-30">Reset</button>
    </div>

</div>

<div class="card">
    <div class="card-body">

        <div class="table-responsive">
            <table id="userTable" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Created At</th>
                        <th></th>
                    </tr>
                </thead>

            </table>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        //$('#role_id').selectize({
        //    plugins: ['remove_button'],
        //});

       $(document).ready(function () {

           var datatable = $('#userTable')
               .DataTable({/* we added this from the other system to have same search and same pagination*/
                   "dom": "<'dt--top-section '<'row'<'col-sm-12 col-md-6 d-flex justify-content-md-start justify-content-center'B><'col-sm-12 col-md-6 d-flex justify-content-md-end justify-content-center mt-md-0 mt-3'f>>>" +
                       "<'table-responsive  'tr>" +
                       "<'dt--bottom-section d-sm-flex justify-content-sm-between text-center'<'dt--pages-count  mb-sm-0 mb-3'i><'dt--pagination'p>>",
                   "buttons": {
                       buttons: [
                           { extend: 'copy', className: 'btn btn-sm' },
                           { extend: 'csv', className: 'btn btn-sm' },
                           { extend: 'excel', className: 'btn btn-sm' },
                           { extend: 'print', className: 'btn btn-sm' }
                       ]
                   },
                   "oLanguage": {
                       "oPaginate": { "sPrevious": 'Perivous', "sNext": 'Next' },
                       "sInfo": "Showing page _PAGE_ of _PAGES_",
                       "sSearch": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>',
                       "sSearchPlaceholder": "Search...",
                       "sLengthMenu": "Results :  _MENU_",
                   },
                    "processing": true,
                    "serverSide": true,
                    "scrollX": true,
                    "stateSave": false,
                    "lengthChange": false,
                    "dom": 'Bfrtip',

                    "buttons": ['copy', 'excel', 'pdf', 'print'],
                    "pageLength":10,
                    "rowId": 'id',
                    "ajax": {
                        "url": "@Url.Action("Index", "EmploymentType")",
                        "type": "POST",
                        "datatype": "json",
                        "dataSrc": "data"
                    },
                    "columns": [
                        {
                            "data": "id",
                            "searchable": true
                        },
                        {
                            "data": "name",
                            "searchable": true
                        },
                        {
                            "data": "created_at_string",
                            "searchable": true
                        },
                        {
                            "data": "id", "searchable": true,
                            fnCreatedCell: function (nTd, sData, oData, iRow, iCol) {
                                var html = "";

                                html += "<a class='edit' id='" + oData.id + "' href='javascript:void(0)' title='Edit'><i class='far fa-edit'></i></a>&nbsp;";
                                html += "<a class='delete' id='" + oData.id + "' href='javascript:void(0)' title='Delete'><i class='fas fa-trash'></i></a>";
                                $(nTd).html("<span class='action-column'>" + html + "</span>");
                            }
                        },
                    ]
                 });

            $('#search').on('click', function () {
                datatable.search($("#text_search").val());
                //datatable.columns(0).search($("#date-form").val());
                //datatable.columns(1).search($("#date-to").val());
                datatable.draw();
            });

            $('#text_search').on('keyup', function (e) {
                if (e.keyCode == 13)
                    $('#search_button').trigger('click');
            });

            $('#reset').on('click', function () {
                $("#text_search").val("");

                $('#search').trigger('click');

            });

            //$('#date-form').bootstrapMaterialDatePicker({
            //    time: false
            //});

            //$('#date-to').bootstrapMaterialDatePicker({
            //    time: false
            //});
           //$("#image").click(function (event) {
           //    var output = document.getElementById('image');
           //    output.src = URL.createObjectURL(event.target.files[0]);
           //});


           $("#add_EmploymentType").click(function () {
               var modal = $('#manage_EmploymentType_modal').clone();
                var action = '@Url.Action("saveEmploymentType", "EmploymentType")';
                modal.find('form').attr('action', action);
               modal.find('#modal_title').text('Add EmploymentType');
                modal.execModal({
                    progressBar: 'progress_bar',
                    progressText: 'progress_text',
                }, function (response) {

                        datatable.draw();

                }, function (response) {

                }, function (dialog) {

                });
            });

            $(document).on("click", ".edit", function () {
                var data = datatable.row($(this).closest('tr')).data();
                console.log(data);
                var modal = $('#manage_EmploymentType_modal').clone();
                var action = '@Url.Action("saveEmploymentType", "EmploymentType")';
                modal.find('form').attr('action', action);
                modal.find('#modal_title').text('Edit EmploymentType');
                modal.execModal({
                    progressBar: 'progress_bar',
                    progressText: 'progress_text',
                }, function (response) {
                        datatable.draw();

                }, function (response) {

                }, function (dialog) {


                        dialog.find('#id').val(data.id);
                        dialog.find('#name').val(data.name);


                });

            });

            $(document).on("click", ".delete", function () {
                var data = datatable.row($(this).closest('tr')).data();
                warningBox("Are you sure you want to delete this EmploymentType (<b>" + data.name +"</b>) ?", function () {
                    $.ajax({
                        type: "GET",
                        url: '@Url.Action("deleteEmploymentType", "EmploymentType")',
                        contentType: "application/json; charset=utf-8",
                        data: { "id": data.id },
                        datatype: "json",
                        success: function (data) {
                            datatable.draw();
                        },
                        error: function () {
                            alert("Dynamic content load failed.");
                        }
                    });
                });
            });

        });

    </script>
}